import random as r

enemies=[
    {
        "NAME":"Tui",
        "HP":r.randint(15,20),
        "SPD":r.randint(40,50),
        "ATK":r.randint(6,10),
        #"CR%":r.randint(100,110)/100
    },
    {
        "NAME":"Kereru",
        "HP":r.randint(20,30),
        "SPD":r.randint(35,45),
        "ATK":r.randint(5,15),
    },
    {
        "NAME":"Weka",
        "HP":r.randint(25,35),
        "SPD":r.randint(30,41),
        "ATK":r.randint(7,14),
    },
    {
        "NAME":"Kakapo",
        "HP":r.randint(30,35),
        "SPD":r.randint(25,35),
        "ATK":r.randint(10,14),
    }
]